server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      routes:
        - id: ms-usuario
          uri: https://ms-usuario-z7jc.onrender.com
          predicates:
            - Path=/api/usuarios/**

        - id: ms-producto
          uri: https://ms-producto-ws46.onrender.com
          predicates:
            - Path=/api/productos/**

        - id: ms-bodega
          uri: https://ms-bodega-3vgn.onrender.com
          predicates:
            - Path=/api/bodegas/**

        - id: ms-pagos
          uri: https://ms-pagos-vdgr.onrender.com
          predicates:
            - Path=/pagos/**

        - id: ms-ventas
          uri: https://ms-ventas-4a5a.onrender.com
          predicates:
            - Path=/api/ventas/**

# Desactivamos Eureka temporalmente para producción en Render, ya que usamos enrutamiento directo
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false